# Generated by Django 2.1.4 on 2019-03-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_comment_obj_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='duration',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.CharField(default='', max_length=10),
        ),
    ]
